# Generated by Django 2.2.2 on 2019-06-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190627_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='diagram',
            field=models.ImageField(null=True, upload_to='diagrams/questions'),
        ),
    ]
