# Generated by Django 2.2.2 on 2019-06-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='diagram',
            field=models.ImageField(null=True, upload_to='diagrams/notes'),
        ),
    ]
