# Generated by Django 2.2.2 on 2019-06-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'free'), ('premium', 'premium'), ('enterprise', 'enterprise')], max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
